### PR TITLE
Fix "view content button" duplicates bug

### LINKED ISSUE #551: Fix Double "View Content" Button on Develop
Project cards have an issue where there are two View Content buttons. 

Replicate by doing the following
1.) Move a project card into the review column
2.) Open the card details
3.) The buttons appear both above and below the reviews

### PR DESCRIPTION
**Pull request by Sbonelo01**
Related issues: [#551 ]

## Description:
The view content buttons no longer duplicates

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: frontend/src/components/pages/CardDetails/Presentation.jsx [hunk 1]
```diff
@@ -200,7 +197,21 @@ export default ({
         ) : (
           <React.Fragment />
         )}
+
+        {/* 
+      We make the view content button default in this view. This slightly changes the order of the
+      buttons that are to be rendered in this page("view content button" will always be at the bottom of the other buttons)
+      The issue of this button having duplicates is resolved.
```
Comment (sheenarbw) [inline frontend/src/components/pages/CardDetails/Presentation.jsx]: Will this comment make sense once the PR is merged? Was it meant to be left in the code? 

If you  want to leave a comment for your reviewers then you could use github's comment feature.

File: frontend/src/components/pages/CardDetails/ProjectDetails.jsx [hunk 2]
```diff
@@ -117,10 +116,10 @@ export default ({
 
       <Reviews reviewIds={project.projectReviews} reviews={reviews} />
 
-      <ViewContentButton
+      {/* <ViewContentButton // This code prohibits the view content button from always showing when it needs to
```
Comment (sheenarbw) [inline frontend/src/components/pages/CardDetails/ProjectDetails.jsx]: Why is this here?

If the code should be removed then can you please remove it?

File: frontend/src/components/pages/CardDetails/Presentation.jsx [hunk 3]
```diff
@@ -163,9 +153,16 @@ export default ({
...
   linkSubmission,
   formErrors,
-}) => {
+}) {
   const classes = useStyles();
 
+  let contentLink, contentItemId;
+  // sometimes card is undefined
+  if (card !== undefined) {
+    contentLink = card.contentItemUrl;
```
Comment (sheenarbw) [inline frontend/src/components/pages/CardDetails/Presentation.jsx]: why is this sometimes called contentItemUrl and other times it's called contentLink? Is there a reason to call one thing by two names?

**Review by sheenarbw — CHANGES_REQUESTED** [review]
Some clean code issues

**Review by sheenarbw — APPROVED** [review]
